### PR TITLE
Add support for including upload summary

### PR DESCRIPTION
**Pull request by ryanjduffy**
* Adds `include-summary` arg, defaulting to `true`, to show this summary

image

### CODE REVIEW

**Review by jaril — APPROVED** [review]

**Comment by jasonLaster** [comment]
From the design side, I think we could probably simplify the UI

| Status | Replay |
|--|--|
| ⬆️  | [breakpoints-01](https://www.youtube.com/watch?v=dQw4w9WgXcQ) | 
| 💾   | [breakpoints-02](https://www.youtube.com/watch?v=dQw4w9WgXcQ) | 
| ❌   | [breakpoints-03](https://www.youtube.com/watch?v=dQw4w9WgXcQ) |

**Comment by ryanjduffy** [comment]
I don't think the icons add clarity alone but collapsing the link into the title is reasonable.

**Comment by jasonLaster** [comment]
Yeah - that's fair.

**Comment by ryanjduffy** [comment]
Now:
---
<h2>Replay Uploads</h2>
<table><tr><th>Title</th><th>Status</th></tr><tr><td>cypress/e2e/cast-alias-spec.ts</td><td>onDisk</td></tr><tr><td><a href="https://app.replay.io/recording/3e891217-81a0-41ae-b879-ab4066be6e3b" target="_blank">Replay of ts-node</a></td><td>uploaded</td></tr></table>

**Pull request merged**
